"project_id": "360467"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
"api_token_env": "CROWDIN_TOKEN"

files:
  [
    {
      "source": "/lib/l10n/bccm_en.arb",
      "translation": "/lib/l10n/bccm_%two_letters_code%.arb",
      "dest": "/BrunstadTV-4.0/intl.arb",
      "skip_untranslated_strings": true,
    },
  ]
