name: brunstadtv_app
description: The app for browsing content from BCC Media

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# major.minor.patch+xxxxxxx
# Note: On play store, any dots in the build
# number (i.e. the number after +) gets removed
version: 5.6.90+2300250

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  provider: ^6.1.2
  js: ^0.7.1
  http: ^1.2.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  flutter_svg: ^2.0.10+1
  auto_route: ^9.2.2
  bccm_player:
    path: submodules/bccm_player
  riverpod: ^2.5.3
  flutter_riverpod: ^2.5.3
  freezed_annotation: ^2.4.4
  collection: ^1.18.0
  package_info_plus: ^8.0.3
  graphql: ^5.1.3
  graphql_flutter: ^5.1.2
  shared_preferences: ^2.3.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  device_info_plus: ^11.0.0
  url_launcher: ^6.3.1
  modal_bottom_sheet: ^3.0.0
  shimmer: ^3.0.0
  flutter_markdown: ^0.7.4
  share_plus: ^10.0.3
  restart_app: ^1.3.2
  app_links: ^6.4.0
  universal_io: ^2.2.2
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.4
  email_validator: ^3.0.0
  open_mail_app_plus: ^0.0.2
  unleash_proxy_client_flutter: ^1.9.6
  html: ^0.15.4
  riverpod_annotation: ^2.5.3
  responsive_framework: ^1.5.1
  intl: ^0.20.2
  focusable_control_builder: ^1.0.2+1
  flutter_to_airplay:
    git:
      url: https://github.com/andreasgangso/flutter_to_airplay.git
      ref: fix/remove-unused-mux
  flutter_cache_manager: ^3.4.1
  extended_image: ^9.1.0
  async: ^2.11.0
  markdown: ^7.2.2
  flutter_animate: ^4.5.0
  simple_shadow: ^0.3.1
  wakelock_plus: ^1.2.8
  preload_page_view: ^0.2.0
  tutorial_coach_mark: ^1.2.11
  bccm_core:
    path: submodules/bccm_flutter/bccm_core
  auto_size_text: ^3.0.0
  webview_flutter: ^4.10.0
  sentry_flutter: ^9.6.0
  bmm_api:
    path: submodules/bccm_flutter/bmm_api/src
  built_collection: ^5.1.1
  dio: ^5.7.0

dependency_overrides:
  js: ^0.7.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  graphql_codegen: ^1.0.1
  custom_lint: any
  riverpod_generator: ^2.4.2
  riverpod_lint: any
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  auto_route_generator: ^9.0.0
  sentry_dart_plugin: ^3.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow/Barlow-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Barlow/Barlow-Bold.ttf
          weight: 700
        - asset: assets/fonts/Barlow/Barlow-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Barlow/Barlow-Medium.ttf
          weight: 500
        - asset: assets/fonts/Barlow/Barlow-Regular.ttf
          weight: 400

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/flavors/prod/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# The SENTRY_AUTH_TOKEN environment variable must be set for this to work.
# https://docs.sentry.io/platforms/flutter/upload-debug/#configure
sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  org: bcc-media-sti
  project: bccm-mobile
  wait_for_processing: false
  log_level: error
  commits: auto
  ignore_missing: true
