name: brunstadtv_app
description: The app for browsing content from BCC Media

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# major.minor.patch+xxxxxxx
# Note: On play store, any dots in the build
# number (i.e. the number after +) gets removed
version: 5.6.29+2300189

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  js: ^0.7.1
  http: ^1.1.0
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  mockito: ^5.2.0
  flutter_svg: ^2.0.2
  auto_route: ^8.2.0
  build_runner: ^2.2.0
  bccm_player:
    path: submodules/bccm_player
  riverpod: ^2.3.4
  flutter_riverpod: ^2.1.1
  freezed_annotation: ^2.1.0
  collection: ^1.18.0
  package_info_plus: ^8.0.0
  table_calendar: ^3.0.7
  graphql: ^5.1.3
  graphql_flutter: ^5.1.0
  shared_preferences: ^2.0.15
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  cloud_firestore: ^5.0.1
  flutter_secure_storage: ^9.0.0
  visibility_detector: ^0.4.0+2
  pull_to_refresh: ^2.0.0
  device_info_plus: ^10.1.0
  flutter_svg_provider: ^1.0.5
  on_screen_ruler: ^0.0.1
  url_launcher: ^6.1.6
  modal_bottom_sheet: ^3.0.0-pre
  #webview_flutter: ^4.0.5
  shimmer: ^3.0.0
  flutter_markdown: ^0.7.2+1
  rudder_sdk_flutter: ^2.5.0
  rudder_sdk_flutter_platform_interface: ^2.2.0
  share_plus: ^9.0.0
  restart_app: ^1.2.1
  app_links: ^6.1.1
  universal_io: ^2.0.4
  jwt_decoder: ^2.0.1
  flutter_appauth: ^6.0.1
  synchronized: ^3.0.1
  clock: ^1.1.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.2.0
  vibration: ^1.7.6
  email_validator: ^3.0.0
  open_mail_app: ^0.4.5
  unleash_proxy_client_flutter: ^1.4.0
  html: ^0.15.2
  riverpod_annotation: ^2.0.4
  image: ^4.0.15
  responsive_framework: ^1.1.1
  intl: ^0.19.0
  focusable_control_builder: ^1.0.2+1
  flutter_to_airplay:
    git:
      url: https://github.com/andreasgangso/flutter_to_airplay.git
      ref: fix/remove-unused-mux
  flutter_image: ^4.1.8
  qr_flutter: ^4.1.0
  focus_debugger: ^0.0.2
  connectivity_plus: ^6.0.0
  flutter_cache_manager: ^3.3.1
  cached_network_image: ^3.3.0
  async: ^2.11.0
  markdown: ^7.1.1
  flutter_animate: ^4.2.0+1
  simple_shadow: ^0.3.1
  wakelock_plus: ^1.1.4
  preload_page_view: ^0.2.0
  tutorial_coach_mark: ^1.2.11
  bccm_core:
    path: submodules/bccm_flutter/bccm_core
  auto_size_text: ^3.0.0
  flutter_widget_from_html_core: ^0.15.1
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.4
  webview_flutter_wkwebview: ^3.14.0
  sentry_flutter: ^8.7.0
  bmm_api:
    path: submodules/bccm_flutter/bmm_api/src
  built_collection: ^5.1.1
  dio: ^5.7.0

dependency_overrides:
  js: ^0.7.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.3.4
  graphql_codegen: ^0.14.0
  custom_lint: any
  riverpod_generator: ^2.3.8
  riverpod_lint: any
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19
  auto_route_generator: ^8.0.0
  sentry_dart_plugin: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # generate: true
  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow/Barlow-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Barlow/Barlow-Bold.ttf
          weight: 700
        - asset: assets/fonts/Barlow/Barlow-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Barlow/Barlow-Medium.ttf
          weight: 500
        - asset: assets/fonts/Barlow/Barlow-Regular.ttf
          weight: 400

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/flavors/prod/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# The SENTRY_AUTH_TOKEN environment variable must be set for this to work.
# https://docs.sentry.io/platforms/flutter/upload-debug/#configure
sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  org: bcc-media-sti
  project: bccm-mobile
  wait_for_processing: false
  log_level: error
  commits: auto
  ignore_missing: true
